### ISSUE TITLE
Get and put value from function if not exists.

### ISSUE THREAD

**Issue by loguntsov** [fogfish/cache#27]
Hello. 
Thank you for your library.

I didn't find simple logic like:
1. Getting value by key.
2. If value is not exists it calculates this value by passed function
3. Put new value into cache and return result (value).

This logic must be atomic as another processes can ask this key at same time.

I hoped to implement this logic by cache:apply function. But can't as this function is always putting data into cache. It doesn't compare old value with new value what can cause useless load.

What solution do you see in this situation ? 
Thanks.

**Comment by loguntsov** [comment]
this is example of implementation logic what i needed:

```

get_and_cache(Name, Key, Fun) ->
  cache:apply(Name, Key, fun
    (undefined) -> Fun();
    (Value) -> Value
  end)
````
but i don't like this way as apply will always update value.

**Comment by fogfish** [comment]
Thank you for raising the interest to the library! Let's try to resolve your issue.

`cache:apply` is exactly the function to make atomic updates. The function does the cache update only when apply function mutate the result. However, the current implementation requires a user defined function to communicate this. The function might look like

```erlang
user_defined_cas(undefined) ->
  %% item do not exists in cache, do something about it
user_defined_cas(OldValue) ->
  case MyBizLogic(OldValue) of
    OldValue ->
       %% we are saying here to cache that value is not changed
       undefined;
   NewValue ->
      NewValue
  end.
```

The reason why I've not implemented this cases into the cache because this is app specific logic to make decision if value is changed or not.

**Comment by loguntsov** [comment]
> The function does the cache update only when apply function mutate the result.
actually you don't right. the code of apply prsented there:

https://github.com/fogfish/cache/blob/2.3.2/src/cache_bucket.erl#L330

it's never checking old value on change.
cache_put also puts data without any checking.

where am i wrong ?

**Comment by loguntsov** [comment]
I have got your idea. But i need return new value to top level.
and MyBizLogic will work in cache process, so it is not good too.

**Comment by fogfish** [comment]
I think you've misunderstood me. The `apply` takes a user defined function. The user defined function is ALWAYs executed in the context of the cache process (this is only a cheap way to ensure serial execution, cheap transactions). 
This user defined function return either some value or undefined. The cache would not be updated if this user defined function return `undefined`.

It is not good idea to run any heavy logic inside the `apply`. It is mainly used for simple math ops or similar. If you need to run a heavy "computation" or I/O then it shall be run in separate process.

**Comment by loguntsov** [comment]
I'm fully agreed with you for separated process for heavy logic. 
I just wanted say:
i need way to get value by key and if it is not presented in cache it should calculate it somehow by calling of function.
This operation must be atomic, otherwise other processes can ask cache and can calculate same thing which will cause race condition.
actually apply is good way, but it doesn't return value if value was not changed.

**Comment by fogfish** [comment]
Great! Let's try to adjust the `apply` so that it provides a sensible api. At the moment the apply function returns response of user defined function. Meaning `undefined` in case of no-changes has been applied. I would propose to return old value from cache. Actually, I can also implement a default check if value is not changed.  If app needs a special "equality" check the apply function might return undefined.

```erlang
cache_apply(Key, Fun, State) ->
   Old = cache_get(Key, State),
   case Fun(Old) of
      undefined  ->
         {Old, State};
      Old ->
         {Old, State};
      Val ->
         {Val, cache_put(Key, Val, undefined, State)}
   end.
```
 
I'll try to craft something like this soonish

**Comment by loguntsov** [comment]
actually i think you can't break defined logic.

```
cache_apply(Key, Fun, State) ->
   Old = cache_get(Key, State),
   case Fun(Old) of
      undefined  ->
         {undefined, State};
      Old ->
         {Old, State};
      Val ->
         {Val, cache_put(Key, Val, undefined, State)}
   end.
```

will work as before with additional logic by checking of changing.

**Comment by loguntsov** [comment]
and thank you very much )
